### ISSUE TITLE
#fetch failed # esprima-fb-3001.1.0-dev-harmony-fb.tgz 

### ISSUE THREAD

**Issue by weimengxi** [Hi-Rube/baoz-ReactNative#11]
切换到cnpm后， npm install 报错：

npm ERR! fetch failed http://r.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz

**Comment by Hi-Rube** [comment]
不切换到cnpm呢

**Comment by weimengxi** [comment]
也不行

**Comment by Hi-Rube** [comment]
@a06062125 let me try

**Comment by weimengxi** [comment]
wait for your good news :)

**Comment by Hi-Rube** [comment]
![image](https://cloud.githubusercontent.com/assets/4507462/7749775/7eb9b362-0002-11e5-865c-ca7f2e75e7a5.png)
我是好的~~
@a06062125

**Comment by weimengxi** [comment]
already done, tks!

**Comment by Hi-Rube** [comment]
@a06062125  能说说是什么原因么  tks~
