### ISSUE TITLE
去阿里实习啦？

### ISSUE THREAD

**Issue by chekun** [Hi-Rube/baoz-ReactNative#20]

**Comment by Hi-Rube** [comment]
@chekun 嗯啊~，你那个spore又扑街了~，刚想自己把spore搭起来，coreseek4 不知道在哪下 T T

**Comment by chekun** [comment]
@Hi-Rube 没服务器了，你在你服务器搞一下啦，哈哈。在coreseek官网下的哈，你要有空，给搞成es搜索也可以哇 :+1:

**Comment by Hi-Rube** [comment]
@chekun 官网都下不了了 所以才拙计啊

**Comment by Hi-Rube** [comment]
把压缩包发我邮箱一个 -> ->

**Comment by chekun** [comment]
@Hi-Rube Check your email!

**Comment by Hi-Rube** [comment]
@chekun 353371737@qq.com

**Comment by chekun** [comment]
@Hi-Rube 从你资料获知邮箱了，应该收到了吧，在你发邮箱之前就发过去了的～

**Comment by Hi-Rube** [comment]
然而并没有啊，难道有延迟 @chekun  353371737@qq.com

**Comment by chekun** [comment]
@Hi-Rube 以重发

**Comment by Hi-Rube** [comment]
@chekun  还是没收到，哭了- -

**Comment by chekun** [comment]
@Hi-Rube 我靠，你QQ邮箱是怎么了！给你

http://7fvdgt.com1.z0.glb.clouddn.com/sharecoreseek4.zip

**Comment by Hi-Rube** [comment]
@chekun 哇咔咔咔 终于放大招了

**Comment by chekun** [comment]
Close for good!
