### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by lanbaba** [Hi-Rube/baoz-ReactNative#22]
No visible @interface for 'RCTRootView' declares the selector 'initWithBundleURL:moduleName:launchOptions:'，我用的xcode为7.0beta5

**Comment by Hi-Rube** [comment]
ok 我升级下xcode看看

**Comment by divefox** [comment]
这个问题有结果了吗？引入文件也不行？

**Comment by Hi-Rube** [comment]
@divefox 你也遇到这个问题么

**Comment by Hi-Rube** [comment]
@divefox @lanbaba    use 
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                    moduleName:@"BaozReact"
                                                    initialProperties:nil
                                                   launchOptions:launchOptions];

**Comment by Hi-Rube** [comment]
@lanbaba @divefox  add initialProperties:nil

**Comment by Hi-Rube** [comment]
@divefox @lanbaba  相关问题都已经解决，try it ~ (^O^)／
